SolutionShop.WebApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SolutionShop.ViewModel.Common;
using System.Threading.Tasks;

namespace AdminApp.Components
{
    public class PagerViewComponent:ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PageResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

SolutionShop.WebApp/Controllers/ProductController.cs
using ApiIntegration.Services;
using Microsoft.AspNetCore.Mvc;
using SolutionShop.ViewModel.Catalog.Products;
using SolutionShop.WebApp.Models;
using System.Threading.Tasks;

namespace SolutionShop.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly ICategoryApiClient categoryApiClient;

        public ProductController  (IProductApiClient productApiClient,ICategoryApiClient categoryApiClient) {
            _productApiClient = productApiClient;
            this.categoryApiClient = categoryApiClient;
        }
            
        public async Task<IActionResult> Detail(int id,string culture)
        {
            var product = await _productApiClient.GetById(id, culture);
            return View(new ProductDetailViewModel()
            {
                Product=product,
                Category=await categoryApiClient.GetById(culture,id)
            });
        }

        public async Task<IActionResult> Category(int id, string culture, int page = 1)
        {
            var products = await _productApiClient.GetPagings(new MGetProductPagingRequest
            {
                CategoryId = id,
                PageIndex = page,
                LanguageId = culture,
                PageSize=10

            });
            return View(new ProductCategoryViewModel() {
            Category=await categoryApiClient.GetById(culture,id),
            Products=products

            });
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {

            return View(new ProductDeleteRequest()
            {
                Id = id
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ProductDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();
            var rs = await _productApiClient.DeleteProduct(request.Id);
            if (rs)
            {
                TempData["result"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Xóa không thành công");

            return View(request);
        }
    }
}

SolutionShop.WebApp/Views/Product/Category.cshtml
@model ProductCategoryViewModel

@{
    ViewData["Title"] = Model.Category.Name + (Model.Products.PageIndex == 1 ? "-" : "-" + _loc["Page"] + "-" + Model.Products.PageIndex);
    ViewData["Description"] = Model.Category.Name + (Model.Products.PageIndex == 1 ? "-" : "-" + _loc["Page"] + "-" + Model.Products.PageIndex);
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture;
}
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;

<ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li class="active">Products Name</li>
</ul>
<h3> @Model.Category.Name <small class="pull-right"> 40 <localize>available products</localize> </small></h3>
<hr class="soft" />
<p>
    Mô tả của ứng dụng (hard)
</p>
<hr class="soft" />
<form class="form-horizontal span6">
    <div class="control-group">
        <label class="control-label alignL"><localize>Sort By</localize> </label>
        <select>
            <option>Priduct name A - Z</option>
            <option>Priduct name Z - A</option>
            <option>Priduct Stoke</option>
            <option>Price Lowest first</option>
        </select>
    </div>
</form>

<div id="myTab" class="pull-right">
    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
</div>
<br class="clr" />
<div class="tab-content">
    <div class="tab-pane" id="listView">
        @for (int i = 0; i < Model.Products.Items.Count; i++)
        {
            var item = Model.Products.Items[i];
            <div class="row">
                <div class="span2">
                    <img src="@(Configuration["BaseAddress"] + @item.ThumbnailImage) " alt="@item.Name" />
                </div>
                <div class="span4">
                    <h3><localize>New | Available</localize></h3>
                    <hr class="soft" />
                    <h5>@item.Name</h5>
                    <p>
                        @item.Description
                    </p>
                    <a class="btn btn-small pull-right" href="product_details.html"><localize>Xem chi tiết</localize></a>
                    <br class="clr" />
                </div>
                <div class="span3 alignR">
                    <form class="form-horizontal qtyFrm">
                        <h3> @item.Price.ToString("C", culture)</h3>
                        <label class="checkbox">
                            <input type="checkbox">  Adds product to compair
                        </label><br />

                        <a href="product_details.html" class="btn btn-large btn-primary"> <localize>Add to</localize> <i class=" icon-shopping-cart"></i></a>
                        <a href="product_details.html" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                    </form>
                </div>
            </div>
            <hr class="soft" />
        }
    </div>

    <div class="tab-pane  active" id="blockView">
        <ul class="thumbnails">
            @for (int i = 0; i < Model.Products.Items.Count; i++)
            {
                var item = Model.Products.Items[i];
                <li class="span3">
                    <div class="thumbnail">
                        <a href="/@culture.Name/@_loc["products"]/@item.Id"><img src="@(Configuration["BaseAddress"] + @item.ThumbnailImage)" alt="@item.Name" /></a>
                        <div class="caption">
                            <h5>@item.Name</h5>
                            <p>
                                @item.Description
                            </p>
                            <h4 style="text-align:center">
                                <a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a>
                                <a class="btn" href="#"><localize>Add to</localize> <i class="icon-shopping-cart"></i></a>
                                <a class="btn btn-primary" href="#">@item.Price.ToString("C", culture)</a>
                            </h4>
                        </div>
                    </div>
                </li>
            }
        </ul>
        <hr class="soft" />
    </div>
</div>

@await Component.InvokeAsync("Pager", Model.Products)
<br class="clr" />

SolutionShop.WebApp/Views/Product/Detail.cshtml
@model ProductDetailViewModel
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture;
}
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;

<ul class="breadcrumb">
    <li><a href="/"><localize>Home</localize></a> <span class="divider">/</span></li>
    <li class="active">@Model.Product.Name</li>
</ul>

<div class="row">
    <div id="gallery" class="span3">
        <a href="@(Configuration["BaseAddress"] + Model.Product.ThumbnailImage)" title="@Model.Product.Name">
            <img src="@(Configuration["BaseAddress"] + Model.Product.ThumbnailImage)" style="width:100%" alt="@Model.Product.Name" />
        </a>
        <div id="differentview" class="moreOptopm carousel slide">
            <div class="carousel-inner">
                <div class="item active">
                    <a href="themes/images/products/large/f1.jpg"> <img style="width:29%" src="themes/images/products/large/f1.jpg" alt="" /></a>
                    <a href="themes/images/products/large/f2.jpg"> <img style="width:29%" src="themes/images/products/large/f2.jpg" alt="" /></a>
                    <a href="themes/images/products/large/f3.jpg"> <img style="width:29%" src="themes/images/products/large/f3.jpg" alt="" /></a>
                </div>
                <div class="item">
                    <a href="themes/images/products/large/f3.jpg"> <img style="width:29%" src="themes/images/products/large/f3.jpg" alt="" /></a>
                    <a href="themes/images/products/large/f1.jpg"> <img style="width:29%" src="themes/images/products/large/f1.jpg" alt="" /></a>
                    <a href="themes/images/products/large/f2.jpg"> <img style="width:29%" src="themes/images/products/large/f2.jpg" alt="" /></a>
                </div>
            </div>
            <!--
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            -->
        </div>

        <div class="btn-toolbar">
            <div class="btn-group">
                <span class="btn"><i class="icon-envelope"></i></span>
                <span class="btn"><i class="icon-print"></i></span>
                <span class="btn"><i class="icon-zoom-in"></i></span>
                <span class="btn"><i class="icon-star"></i></span>
                <span class="btn"><i class=" icon-thumbs-up"></i></span>
                <span class="btn"><i class="icon-thumbs-down"></i></span>
            </div>
        </div>
    </div>
    <div class="span6">
        <h3>@Model.Product.Name</h3>
        <small>@Model.Product.Description</small>
        <hr class="soft" />
        <form class="form-horizontal qtyFrm">
            <div class="control-group">
                <label class="control-label"><span>$222.00</span></label>
                <div class="controls">
                    <input type="number" class="span1" placeholder="Qty." />
                    <button type="submit" class="btn btn-large btn-primary pull-right"> <localize>Add to</localize> <i class=" icon-shopping-cart"></i></button>
                </div>
            </div>
        </form>

        <hr class="soft" />
        <h4>100 items in stock</h4>
        <form class="form-horizontal qtyFrm pull-right">
            <div class="control-group">
                <label class="control-label"><span>Color</span></label>
                <div class="controls">
                    <select class="span2">
                        <option>Black</option>
                        <option>Red</option>
                        <option>Blue</option>
                        <option>Brown</option>
                    </select>
                </div>
            </div>
        </form>
        <hr class="soft clr" />
        <p>
            @Html.Raw(Model.Product.Details)
        </p>
        <a class="btn btn-small pull-right" href="#detail"><localize>More Details</localize></a>
        <br class="clr" />
        <a href="#" name="detail"></a>
        <hr class="soft" />
    </div>

    <div class="span9">
        <ul id="productDetail" class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab"><localize>Product Details</localize></a></li>
            <li><a href="#profile" data-toggle="tab"><localize>Related Products</localize></a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="home">
                <h4>Product Information</h4>
                @Html.Raw(Model.Product.Details)
            </div>
            <div class="tab-pane fade" id="profile">
                <div id="myTab" class="pull-right">
                    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
                    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
                </div>
                <br class="clr" />
                <hr class="soft" />
                <div class="tab-content">
                    <div class="tab-pane" id="listView">
                        <div class="row">
                            <div class="span2">
                                <img src="themes/images/products/4.jpg" alt="" />
                            </div>
                            <div class="span4">
                                <h3>New | Available</h3>
                                <hr class="soft" />
                                <h5>Product Name </h5>
                                <p>
                                    Nowadays the lingerie industry is one of the most successful business spheres.We always stay in touch with the latest fashion tendencies -
                                    that is why our goods are so popular..
                                </p>
                                <a class="btn btn-small pull-right" href="product_details.html">View Details</a>
                                <br class="clr" />
                            </div>
                            <div class="span3 alignR">
                                <form class="form-horizontal qtyFrm">
                                    <h3> $222.00</h3>
                                    <label class="checkbox">
                                        <input type="checkbox">  Adds product to compair
                                    </label><br />
                                    <div class="btn-group">
                                        <a href="product_details.html" class="btn btn-large btn-primary"> Add to <i class=" icon-shopping-cart"></i></a>
                                        <a href="product_details.html" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <hr class="soft" />
                    </div>
                    <div class="tab-pane active" id="blockView">
                        <ul class="thumbnails">
                            <li class="span3">
                                <div class="thumbnail">
                                    <a href="product_details.html"><img src="themes/images/products/10.jpg" alt="" /></a>
                                    <div class="caption">
                                        <h5>Manicure &amp; Pedicure</h5>
                                        <p>
                                            Lorem Ipsum is simply dummy text.
                                        </p>
                                        <h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">&euro;222.00</a></h4>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <hr class="soft" />
                    </div>
                </div>
                <br class="clr">
            </div>
        </div>
    </div>
</div>